[project]
name = "nor"
version = "0.1.0"
license = "MIT"
description = "NoR is a Python-based mini-language designed for quickly and easily creating graphs for academic papers."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lark>=1.2.2",
    "matplotlib>=3.10.3",
]
